name: CI & Release

on:
  pull_request:
  push:
    branches: ['master', 'alpha', 'beta']

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          version: '10'
          run_install: true

      - name: Install dependencies
        run: pnpm install

      - name: Linting
        run: pnpm lint

      - name: Unit Tests
        run: pnpm test:unit:coverage

      - name: Test types
        run: pnpm test:types

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check size
        run: pnpm test:size

  release:
    if: github.event_name == 'push'
    needs: check-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: '10'
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
